### ISSUE TITLE
Failed to restart mihomo.service: Unit mihomo.service not found.

### ISSUE THREAD

**Issue by syx-413** [spencerwooo/mihoro#157]
**Describe the bug**
When I try to update mihoro, the system reports that the mihomo.service unit is not found.

**To Reproduce**
1.Open the terminal
2.Enter and run the command mihoro update
3. Observe the error message: `Failed to restart mihomo.service: Unit mihomo.service not found`.

**Expected behavior**
I expect mihoro to update normally and mihomo.service to be successfully found and restarted.
**Screenshots**
![截图 2024-01-02 22-59-20](https://github.com/spencerwooo/mihoro/assets/104879935/5c460b94-163c-4948-8dbc-bbe4b8aace7a)
![截图 2024-01-02 22-59-37](https://github.com/spencerwooo/mihoro/assets/104879935/824fed24-9c24-4e3a-874a-1b8a64694599)

**Additional context**
I am using the Arch Linux operating system with a x86_64-unknown-linux-gnu architecture. I encountered this problem when trying to update mihoro.

**Comment by spencerwooo** [comment]
Did you run `mihoro setup` after installation? Please check for the path `user_systemd_root` defined inside `mihoro.toml` and see if the systemd file has been created.

**Comment by spencerwooo** [comment]
Sorry if setup instructions are not clear. I am still transitioning `mihoro` from the original `clashrup` and not all documentation are refactored.

**Comment by syx-413** [comment]
> Did you run `mihoro setup` after installation? Please check for the path `user_systemd_root` defined inside `mihoro.toml` and see if the systemd file has been created.安装后是否运行了 `mihoro setup` ？请检查 `mihoro.toml` 中定义的路径 `user_systemd_root` ，并查看是否已创建systemd文件。
![image](https://github.com/spencerwooo/mihoro/assets/104879935/f5125a23-01d5-4676-acb5-c410969ffca2)
![image](https://github.com/spencerwooo/mihoro/assets/104879935/d850df52-e8ad-4baf-a4d5-42c79c7c01c4)
![image](https://github.com/spencerwooo/mihoro/assets/104879935/93ce7289-8bd1-43bf-a8ab-b45b4240453d)


I referred clashrup(maybe) it still dont work.
Perhaps a manual is needed.

**Comment by spencerwooo** [comment]
This project (`mihoro`) only references `~/.config/systemd/user/mihomo.service` by default. I think you need to perform a full removal of `clashrup` components and `clash` components, and run `mihoro setup` again. Please try following these steps:

* (If you still have `clashrup` installed): `clashrup uninstall`
* Uninstall mihoro: `mihoro uninstall`
* Remove `mihomo`: `rm -R ~/.local/bin/mihomo ~/.config/mihomo`
* Remove `clash`: `rm -R ~/.local/bin/clash ~/.config/clash`
* Remove `clash.service`: `rm -R ~/.config/systemd/user/clash.service`
* Double check `mihoro` config (`~/.config/mihoro.toml`) and reinstall mihoro: `mihoro setup`

Please provide your `~/.config/mihoro.toml` and `~/.config/systemd/user/mihomo.service` if things are still not working. (Please redact sensitive information.)

**Comment by syx-413** [comment]
![image](https://github.com/spencerwooo/mihoro/assets/104879935/d0e067dc-866a-4a3d-b1d8-1877510b1599)
## mihoro.toml
![截图 2024-01-04 13-43-28](https://github.com/spencerwooo/mihoro/assets/104879935/e95c3462-fb63-4400-9ad7-fc1bcc3b6055)

When I use the dashboard, it will appear，is it because I am using a dual system?i

![image](https://github.com/spencerwooo/mihoro/assets/104879935/bb0c0bc9-3a50-4824-8749-816825b4de8e)

**Comment by spencerwooo** [comment]
Can you try executing `~/.local/bin/mihomo` directly? What are the outputs?

**Comment by syx-413** [comment]
> Can you try executing `~/.local/bin/mihomo` directly? What are the outputs?

![image](https://github.com/spencerwooo/mihoro/assets/104879935/3ee2f77d-6ce1-4a87-8ecd-9adf4df7698a)

**Comment by spencerwooo** [comment]
I'm not sure what's wrong, everything seems ok :(
