### ISSUE TITLE
Mihomo mixed-port config support

### ISSUE THREAD

**Issue by fty1777** [spencerwooo/mihoro#160]
**Is your feature request related to a problem? Please describe.**
Thanks for your fabulous work. The CLI itself is smooth, lightweight and extremely convenient and I love it. Mihomo support setting mixed-port which can be used for both http and socks port. Mohoro seems not supporting it now.

**Describe the solution you'd like**
Add an additional config item into config.rs to parse the mixed-port config to mihomo. I can also help to create the PR to contribute if the maintainers have no free time to add this feature.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by spencerwooo** [comment]
You are more than welcome to create the PR ;)
