### ISSUE TITLE
Failed to connect to bus

### ISSUE THREAD

**Issue by BSTluo** [spencerwooo/mihoro#164]
After running `mihoro setup`, I received the message `Failed to connect to bus`. The specific details are as follows:

![image](https://github.com/user-attachments/assets/6c3c28af-9fcf-47b8-9675-b14831ec2bb9)

**Comment by spencerwooo** [comment]
Seems that systemd is not working as it is failing at creating the `mihoro` systemd service.

`mihoro` tries to create the systemd service on the user side, i.e., `systemctl --user ...`. Can you try a

```bash
systemctl --user status
```

and see if the problem persists?

**Comment by BSTluo** [comment]
The reason for the issue is likely a malfunction in my system! Thank you for your help!

**Comment by guigeng** [comment]
> The reason for the issue is likely a malfunction in my system! Thank you for your help!

请问怎么解决的？

**Comment by spencerwooo** [comment]
@guigeng Could you check the superuser question link I posted above and try running mihoro with a user account other than root? If not resolved, please post a new issue :)
